demo:
  target: dev
  outputs:
    dev:
      type: postgres
      threads: 1
      host: <your_host>
      port: 5432
      user: <your_user>
      pass: <your_pass>
      dbname: <your_db>
      schema: <your_schema>

    prod: # your production environment
      type: postgres
      threads: 1
      host: <your_host>
      port: 5432
      user: <your_user>
      pass: <your_pass>
      dbname: <your_db>
      schema: <your_schema>

elementary:
 outputs:
   default:
     type: postgres
     host: <your_host>
     port: 5432
     user: elementary
     password: <you password>
     dbname: <your_db>
     schema: <your_schema>
