version: '3'
services:
  postgres:
    image: postgres:13
    environment:
        POSTGRES_USER: prefect
        POSTGRES_PASSWORD: prefect
        POSTGRES_DB : prefect
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql # 新增挂载 init.sql 文件
    ports:
      - "15432:5432"
    restart: always
    
  prefect:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      PREFECT__BACKEND: server
      PREFECTHOME: /work/prefect
      PREFECT_API_DATABASE_CONNECTION_URL: "postgresql+asyncpg://prefect:prefect@postgres:5432/prefect"
      CREDENTIALS_BLOCK_NAME: <your  CREDENTIALS_BLOCK_NAME>
    ports:
      - "4200:4200"
    depends_on:
      - postgres
    command: sh -c "sleep 5 && prefect server database reset -y && prefect server database upgrade -y && sh /work/start.sh"

